#!/usr/bin/env python3

import os.path
import glob

with open('Cargo.toml', 'w') as f:
    print("""# Auto generated with `./script/gen-workspace`

[workspace]
members = [""", file=f)

    chapter = 'chapter-01'

    for path in sorted(list(glob.glob('chapter-*/**/Cargo.toml', recursive=True))):
        new_chapter = path.split('/')[0]
        if new_chapter != chapter:
            print('', file=f)
            chapter = new_chapter

        dirname = os.path.dirname(path)

        line_start = '    '

        if dirname.endswith('NO_COMPILE'):
            line_start = '#   '

        print(f'{line_start}"{dirname}",', file=f)

    print(']', file=f)


# Note: do not add `recursive=True` to this glob call because we only want to
# rewrite the crate names for listing crates that have one level of nesting. If
# they have more than this they must write their own crate names
for path in glob.glob('chapter-*/**/Cargo.toml'):
    chapter = None
    listing = None

    for component in path.split('/'):
        if component.startswith('chapter'):
            chapter = component
        elif component.startswith('listing'):
            listing = component

    if listing is None or chapter is None:
        continue

    listing_parts = listing.split('_')

    name_line = f'name = "{chapter}-{listing_parts[0]}-{listing_parts[1]}"\n'

    new_contents = ''
    with open(path) as f:
        line = f.readline()
        while line:
            if line.startswith('name ='):
                new_contents += name_line
            else:
                new_contents += line

            line = f.readline()


    with open(path, 'w') as f:
        f.write(new_contents)

